### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_two_sample.permutation_test'

### ISSUE THREAD

**Issue by AndreydeAguiarSalvi** [josipd/torch-two-sample#9]
I receive this error while trying to do this:
from torch_two_sample import SmoothFRStatistic
There was no error in the installation. Inside the torch_to_sample folder, I noticed that there is a permutation_test.pyx file, but not a .py file.
The complete stack trace:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/someone/A00AA3760AA347DC/torch-two-sample/torch_two_sample/__init__.py", line 1, in <module>
    from .statistics_diff import (
  File "/media/someone/A00AA3760AA347DC/torch-two-sample/torch_two_sample/statistics_diff.py", line 9, in <module>
    from .permutation_test import permutation_test_tri, permutation_test_mat
ModuleNotFoundError: No module named 'torch_two_sample.permutation_test'

**Comment by nkamath5** [comment]
Was anyone able to solve this issue?

**Comment by nkamath5** [comment]
Running the setup & install per the readme file solved this issue for me

> ### Installation

After installing PyTorch, you can install the package with:

```
python setup.py install
```

### Testing

To run the tests you simply have to run:

```
python setup.py test
```

**Comment by nkamath5** [comment]
Running the setup & install per the readme file solved this issue for me, to quote from the readme:

### Installation

After installing PyTorch, you can install the package with:

```
python setup.py install
```

### Testing

To run the tests you simply have to run:

```
python setup.py test
```

**Comment by elidub** [comment]
It seems that I have to download xcode for this in order to work. Is that necessary or are other ways to use this package?

**Comment by Jot-De** [comment]
A PYX file is a source code written in the Python-like language Pyrex.
I had to install pyrex in order for this package to work
`pip install git+https://github.com/bhokansonfasig/pyrex#egg=pyrex
`
